function A = readlayer(layerfile)
% A = readlayer(layerfile)
%
% Reads a file of the form (layername)_{A,GE,GI,V,Vth}_last.pvp file,
% generated by PetaVision
%
% layerfile is the filename
% A is an i-by-j-by-n array.  The third index corresponds to the feature index.
%
% Note:  due to what I think is a bug in PetaVision's fileio.cpp file,
% if nPad is greater than zero, the file created is large enough to hold
% an (nx+2*nPad)-by-(ny+2*nPad)-by-nf array, but only the first nx*ny*nf
% values are meaningful.  The 

fid = fopen(layerfile);
if fid == -1
    error('readlayer:cantopenfile','Can''t open %s',layerfile);
end%if fid

[hdr, count] = fread(fid,20,'int32');
if count ~= 20
    fclose(fid);
    error('readlayer:cantreadheader','Can''t read header for %s',layerfile);
end%if count

nf = hdr(6);
nx = hdr(4);
ny = hdr(5);

sz = hdr(8);
npad = hdr(17);

if sz ~= (nx+2*npad)*(ny+2*npad)*nf*4
    fclose(fid);
    error('readlayer:badheader',...
          'The header does not appear to be correct for a layer .pvp file');
end%if sz

[A, count] = fread(fid, nx*ny*nf, 'single');
if count ~= nx*ny*nf
    fclose(fid);
    error('readlayer:cantreaddata','Can''t read data for %s',layerfile);
end%if count

fclose(fid);

A = reshape(A,[nf,nx,ny]);

A = permute(A,[2 3 1]);

