function A = readlayer(layerfile)
% A = readlayer(layerfile)
%
% Reads a (layername)_{A,GE,GI,V,Vth}_last.pvp file generated by PetaVision 
% layerfile is the filename
% A is an i-by-j-by-n array.  The third index corresponds to the feature index.

fid = fopen(layerfile);
if fid == -1
    error('readlayer:cantopenfile','Can''t open %s',activityfile);
end

hdr = fread(fid,20,'int32');

sz = hdr(8);

A = fread(fid, sz, 'single');

nf = hdr(6);
nx = hdr(4);
ny = hdr(5);
npad = hdr(17);
d1 = nx*ny*nf*4;
d2 = (nx+2*npad)*(ny+2*npad)*nf*4;

if d1 == sz
    A = reshape(A,[nf,nx,ny]);
elseif d2 == sz
    A = reshape(A,[nf,nx+2*npad,ny+2*npad]);
else
    fclose(fid);
    error('readlayer:unfamiliarlength',...
          'The length of %s doesn''t make sense.',layerfile);
end

fclose(fid);

A = permute(A,[2 3 1]);

