#
# pv_ifc.py
#
#  Created on: Aug 16, 2008
#      Author: dcoates

PV_ACTION_INIT=1
PV_ACTION_ADD_LAYER=2
PV_ACTION_SET_LAYER_PARAMS=3
PV_ACTION_ADD_CONNECTION=4
PV_ACTION_RUN=5
PV_ACTION_SET_PARAMS=6
PV_ACTION_SET_INPUT_FILENAME=7
PV_ACTION_INJECT=8
PV_ACTION_MEASURE=9
PV_ACTION_FINALIZE=10
PV_ACTION_SETUP=11

PV_HANDLER_LIF=1
PV_HANDLER_READFILE=2
PV_HANDLER_GAUSS2D=3
PV_HANDLER_THRU=4
PV_HANDLER_COCIRC1D=5
PV_HANDLER_COCIRC_K=6
PV_HANDLER_CENTER_SURR=7
PV_HANDLER_PROB_FIRE=8
PV_HANDLER_LIF2=9
PV_HANDLER_GAUSS2DX=10
PV_HANDLER_COCIRC_K2=11

PV_BUFFER_V=0
PV_BUFFER_PHI=1
PV_BUFFER_G_I=2
PV_BUFFER_G_E=3
PV_BUFFER_F=4

PV_CONNECTION_FLAG=100
