# Base Io build system
# Written by Jeremy Tregunna <jeremy.tregunna@me.com>
#
# Find libsndfile.

FIND_PATH(LIBSNDFILE_INCLUDE_DIR sndfile.h PATHS /usr/local/Cellar/libsndfile/include/)

SET(LIBSNDFILE_NAMES ${LIBSNDFILE_NAMES} sndfile libsndfile)
FIND_LIBRARY(LIBSNDFILE_LIBRARY NAMES ${LIBSNDFILE_NAMES} PATH)

IF(LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)
   SET(LIBSNDFILE_FOUND TRUE)
ENDIF(LIBSNDFILE_INCLUDE_DIR AND LIBSNDFILE_LIBRARY)

# following two lines added for PetaVision to get LibSndFile_FIND_REQUIRED to work
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBSNDFILE DEFAULT_MSG LIBSNDFILE_LIBRARY LIBSNDFILE_INCLUDE_DIR)

# IF(LIBSNDFILE_FOUND)
#    MESSAGE(STATUS "Found LibSndFile: ${LIBSNDFILE_LIBRARY}")
# ELSE(LIBSNDFILE_FOUND)
#    IF(LibSndFile_FIND_REQUIRED)
#       MESSAGE(FATAL_ERROR "Could not find sndfile")
#    ELSE(LibSndFile_FIND_REQUIRED)
#       IF(NOT LibSndFile_FIND_QUIETLY)
#          MESSAGE(STATUS "Skipping sndfile")
#       ENDIF(NOT LibSndFile_FIND_QUIETLY)
#    ENDIF(LibSndFile_FIND_REQUIRED)
# ENDIF (LIBSNDFILE_FOUND)
