
object_type = {"2FC"; "4FC"; "6FC"; "8FC"};
clip_name = cell(3,1);
clip_name{1} = "a";
clip_name{2} = "d";
clip_name{3} = "t";
version_ids = [1:16];
version_str = cell(length(version_ids),1);
for i_version = 1 : length(version_ids)
  version_str{i_version} = num2str(version_ids(i_version), "%3.3i");   
endfor

global PVP_VERBOSE_FLAG
PVP_VERBOSE_FLAG = 0;

global pvp_home_path
global pvp_workspace_path
global pvp_mlab_path
global pvp_clique_path
pvp_home_path = ...
    [filesep, "home", filesep, "garkenyon", filesep];
pvp_workspace_path = ...
    [pvp_home_path, "workspace-indigo", filesep];
pvp_mlab_path = ...
    [pvp_workspace_path, "PetaVision", filesep, "mlab", filesep];
pvp_clique_path = ...
    [pvp_workspace_path, "Clique2", filesep];


DATASET_ID = "amoeba"; %%"Heli"; %% "Tower"; %% "Tailwind"; %% 
dataset_id = tolower(DATASET_ID); %% 
FLAVOR_ID = "3way"; %%"Training"; %% "Challenge"; %% "Formative"; %%  
flavor_id = tolower(FLAVOR_ID); %% 
pvp_repo_path = ...
    [filesep, "mnt", filesep, "data1", filesep];
pvp_program_path = ...
    [pvp_repo_path, "PetaVision", filesep, ...
     DATASET_ID, filesep, ...
     FLAVOR_ID, filesep];
pvp_input_path = ...
    [pvp_clique_path, "input", filesep, ...
     DATASET_ID, filesep, ...
     FLAVOR_ID, filesep];
%%    pvp_clip_name = "a"; %% "045"; %%
%%    pvp_object_type =  "4FC"; %% "Car"; %%
pvp_num_ODD_kernels =  1; %% 3; %%
pvp_bootstrap_str =  ""; %% "_bootstrap"; %%
pvp_edge_type =  ""; %% "canny"; %%
%%pvp_version_str =  "1"; %%
pvp_params_template = ...
    [pvp_clique_path, ...
     "templates", filesep, ...
     DATASET_ID, filesep, ...
     FLAVOR_ID, filesep, ...
     DATASET_ID, "_", FLAVOR_ID, "_", ...
     "template.params"];
pvp_frame_size =  [256, 256];
pvp_num_frames =  625;

output_activity_path = ...
    [pvp_program_path, ...
     "activity", filesep];
mkdir(output_activity_path);

pvp_list_path = ...
    [pvp_program_path, ...
     "list", filesep];

for i_object = 1 : length(object_type)
  disp(object_type{i_object});
  
  output_object_path = ...
      [output_activity_path, ...
       object_type{i_object}, filesep];
  mkdir(output_object_path);

  input_object_path = ...
      [pvp_input_path, ...
       object_type{i_object}, filesep];
  mkdir(input_object_path);

  list_object_path = ...
      [pvp_list_path, ...
       object_type{i_object}, filesep];

  for i_clip = 1 : length(clip_name)
    disp(clip_name{i_clip});
    
    output_clip_path = ...
	[output_object_path, ...
	   clip_name{i_clip}, filesep];
    mkdir(output_clip_path);
    
    input_clip_path = ...
	[input_object_path, ...
	   clip_name{i_clip}, filesep];
    mkdir(input_clip_path);
    
    list_clip_path = ...
	[list_object_path, ...
	   clip_name{i_clip}, filesep];
    list_path = list_clip_path;

    for i_version = 1 : length(version_str)
      disp(version_str{i_version});
      
      output_version_path = ...
	  [output_clip_path, ...
	   version_str{i_version}, filesep]);
      mkdir(output_version_path);
      output_path = output_version_path;
      
      input_version_path = ...
	  [input_clip_path, ...
	   version_str{i_version}, filesep]);
      mkdir(input_version_path);
      input_path = input_version_path;


      pvp_fileOfFrames_path = ...
	  [list_path];
      pvp_fileOfFrames_file = ...
	  [object_type{i_object}, "_", clip_name{i_clip}, "_", version_str{i_version}, "_", "fileOfFilenames.txt"];
      pvp_fileOfFrames = ...
	  [pvp_fileOfFrames_path, pvp_fileOfFrames_file];


      params_filename = ...
	  [DATASET_ID, ...
	   "_", ...
	   FLAVOR_ID, ...
	   "_", ...
	   object_type{i_object}, ...
	   num2str(pvp_num_ODD_kernels), pvp_bootstrap_str, ...
	   "_", ...
	   pvp_clip_name{i_clip}, ...
	   "_", ...
	   pvp_edge_type, ...
	   version_str{i_version}, ...
	   ".params"];



      [pvp_params_file, pvp_params_path] = ...
	  pvp_makeParams2(DATASET_ID, ...
			  FLAVOR_ID, ...
			  pvp_repo_path, ...
			  pvp_program_path, ...
			  input_path, ...
			  clip_name{i_clip}, ...
			  object_type{i_object}, ...
			  pvp_num_ODD_kernels, ...
			  pvp_bootstrap_str, ...
			  pvp_edge_type, ...
			  version_str{i_version}, ...
			  pvp_params_template, ...
			  pvp_frame_size, ...
			  pvp_num_frames, ...
			  list_path, ...
			  pvp_fileOfFrames, ...
			  output_path, ...
			  params_filename);

      
    endfor
  endfor
endfor %% i_clip
