
clip_ids = [45]; %% [26:50]; %% [7:17,21:22,30:31];
clip_name = cell(length(clip_ids),1);
for i_clip = 1 : length(clip_name)
  clip_name{i_clip} = num2str(clip_ids(i_clip), "%3.3i");
endfor

global PVP_VERBOSE_FLAG
PVP_VERBOSE_FLAG = 0;

global pvp_home_path
global pvp_mlab_path
global pvp_clique2_path

pvp_home_path = ...
    [filesep, "Users", filesep, "gkenyon", filesep];
pvp_mlab_path = ...
    [pvp_home_path, "workspace-indigo", filesep, "PetaVision", filesep, "mlab", filesep];
pvp_clique2_path = ...
    [pvp_home_path, "workspace-indigo", filesep, "Clique2", filesep];

NEOVISION_DATASET_ID = "Heli"; 
neovision_dataset_id = tolower(NEOVISION_DATASET_ID); %% 
NEOVISION_DISTRIBUTION_ID = "Training";
neovision_distribution_id = tolower(NEOVISION_DISTRIBUTION_ID); %% 
pvp_repo_path = ...
    [pvp_home_path, "NeoVision2", filesep];
pvp_program_path = ...
    [pvp_repo_path, "neovision-programs-petavision", filesep];
pvp_object_type =  "Car"; %%
pvp_num_ODD_kernels =  3; %%
pvp_edge_type =  "canny"; %%
pvp_params_template = ...
    [pvp_clique2_path, filesep, "input", filesep ...
     NEOVISION_DATASET_ID, filesep, ...
     NEOVISION_DISTRIBUTION_ID, filesep, ...
     "templates", filesep, ...
     NEOVISION_DATASET_ID, "_", NEOVISION_DISTRIBUTION_ID, "_", ...
     pvp_object_type, num2str(pvp_num_ODD_kernels), "_", ...
     "_template.params"];
pvp_frame_size =  [1080 1920]; %%
pvp_fileOfFrames_path = ...
    [list_path, NEOVISION_DATASET_ID, filesep, NEOVISION_DISTRIBUTION_ID, filesep, ...
     pvp_clip_name, filesep, pvp_edge_type, filesep];
pvp_fileOfFrames_prefix = ...
    [NEOVISION_DATASET_ID, "_", NEOVISION_DISTRIBUTION_ID, "_", pvp_clip_name, "_", pvp_edge_type, "_", "frames"];
pvp_fileOfFrames = ...
    [pvp_fileOfFrames_path, pvp_fileOfFrames_prefix, ".txt"];

for i_clip = 1 : length(clip_name)
  disp(clip_name{i_clip});


  [pvp_params_file, ...
   pvp_params_dir] = ...
      pvp_makeParams(NEOVISION_DATASET_ID, ...
		     NEOVISION_DISTRIBUTION_ID, ...
		     pvp_repo_path, ...
		     pvp_program_path, ...
		     clip_name{i_clip}, ...
		     pvp_object_type, ...
		     pvp_num_ODD_kernels, ...
		     pvp_edge_type, ...
		     pvp_params_template, ...
		     pvp_frame_size, ...
		     pvp_num_frames, ...
		     pvp_list_path, ...
		     pvp_fileOfFrames);

endfor