object_ids = [26:50]; 
object_name = cell(length(object_ids),1);
for i_object = 1 : length(object_name)
  object_name{i_object} = num2str(object_ids(i_object), "%3.3i");
endfor
for i_object = 1 : length(object_name)
disp(object_name{i_object});
[pvp_params_file, ...
 pvp_params_dir] = ...
    pvp_makeParams(NEOVISION_DATASET_ID, ...
		   NEOVISION_DISTRIBUTION_ID, ...
		   pvp_repo_path, ...
		   pvp_program_path, ...
		   pvp_params_template, ...
		   pvp_clip_name, ...
		   pvp_object_type, ...
		   pvp_num_ODD_kernels, ...
		   pvp_edge_type, ...
		   pvp_frame_size, ...
		   pvp_fileOfFrames)

csv_file = ...
  ["/mnt/data1/repo/neovision-programs-petavision/Heli/Challenge/results/", object_name{i_object}, "/Car3/canny2/", "Heli_", object_name{i_object}, "_PetaVision_", "Car", "_002", ".csv"]

csv_repo = ...
  ["/mnt/data1/repo/neovision-results-challenge-heli/", object_name{i_object}, filesep]
mkdir(csv_repo);
copyfile(csv_file, csv_repo)
endfor



