
object_type = {"Car"}; %%{"2FC"; "4FC"; "6FC"; "8FC"};

%% clip_name stores the directories that contain the individual frames
clip_flag = false;
if clip_flag
  clip_ids = [1:50]; %% [7:17,21:22,30:31];
  clip_name = cell(length(clip_ids),1);
  for i_clip = 1 : length(clip_name)
    clip_name{i_clip} = num2str(clip_ids(i_clip), "%3.3i");
  endfor
else
  clip_name = cell(1);
  clip_name{1} = "Car_bootstrap0";
endif

%% version_str stores the training or testing run index 
version_ids = [1:8];
version_str = cell(length(version_ids),1);
for i_version = 1 : length(version_ids)
  version_str{i_version} = num2str(version_ids(i_version), "%3.3i");   
endfor

global PVP_VERBOSE_FLAG
PVP_VERBOSE_FLAG = 0;

global pvp_home_path
global pvp_workspace_path
global pvp_mlab_path
global pvp_clique_path
pvp_home_path = ...
    [filesep, "home", filesep, "gkenyon", filesep];
pvp_workspace_path = ...
    [pvp_home_path, "workspace-indigo", filesep];
pvp_mlab_path = ...
    [pvp_workspace_path, "PetaVision", filesep, "mlab", filesep];
pvp_clique_path = ...
    [pvp_workspace_path, "Clique2", filesep];


DATASET_ID = "Heli"; %% "amoeba"; %%"Tower"; %% "Tailwind"; %% 
dataset_id = tolower(DATASET_ID); %% 
FLAVOR_ID = "Training"; %% "3way"; %%"33x33"; %% "Challenge"; %% "Formative"; %%  
flavor_id = tolower(FLAVOR_ID); %% 
pvp_repo_path = ...
    [filesep, "mnt", filesep, "data", filesep, "repo", filesep];
pvp_petavision_path = ...
    [pvp_repo_path, "neovision-programs-petavision", filesep]; %%, ...
pvp_dataset_path = ...
    [pvp_petavision_path, ...
     DATASET_ID, filesep]; %%, ...
mkdir(pvp_dataset_path);
pvp_flavor_path = ...
    [pvp_dataset_path, ...
     FLAVOR_ID, filesep]; %%, ...
mkdir(pvp_flavor_path);
pvp_program_path = ...
    pvp_flavor_path;
mkdir(pvp_program_path);

pvp_input_path2 = ...
    [pvp_clique_path, "input", filesep]; %%, ...
pvp_input_path3 = ...
    [pvp_input_path2, ...
     DATASET_ID, filesep]; %%, ...
mkdir(pvp_input_path3);
pvp_input_path = ...
    [pvp_input_path3, ...
     FLAVOR_ID, filesep];
mkdir(pvp_input_path);

pvp_num_ODD_kernels =  1; %% 3; %%
pvp_num_ODD_kernels_str = "";
if pvp_num_ODD_kernels > 1
  pvp_num_ODD_kernels_str = num2str(pvp_num_ODD_kernels);
endif
pvp_bootstrap_str = ""; %% "_bootstrap0"; %%  
pvp_edge_type = "canny"; %% ""; %% 
pvp_frame_size =  [256, 256];
pvp_num_frames =  12294; %%625;

output_activity_path = ...
    [pvp_program_path, ...
     "activity", filesep];
mkdir(output_activity_path);

pvp_list_path = ...
    [pvp_program_path, ...
     "list", "_", pvp_edge_type, filesep];

for i_object = 1 : length(object_type)
  disp(object_type{i_object});
  
  pvp_params_template = ...
      [pvp_clique_path, ...
       "templates", filesep, ...
       DATASET_ID, filesep, ...
       FLAVOR_ID, filesep, ...
       object_type{i_object}, pvp_num_ODD_kernels_str, filesep, ...
       pvp_edge_type, filesep, ...
       DATASET_ID, "_", FLAVOR_ID, "_", object_type{i_object}, pvp_num_ODD_kernels_str, "_", pvp_edge_type, "_", ...
       "template.params"];
  
  output_object_path2 = ...
      [output_activity_path, ...
       object_type{i_object}, pvp_num_ODD_kernels_str, filesep];
  mkdir(output_object_path2);
  output_object_path = ...
      [output_object_path2, ...
       pvp_edge_type, filesep];
  mkdir(output_object_path);

  input_object_path2 = ...
      [pvp_input_path, ...
       object_type{i_object}, pvp_num_ODD_kernels_str, filesep];
  mkdir(input_object_path2);
  input_object_path = ...
      [input_object_path2, ...
       pvp_edge_type, filesep];

  list_object_path = ...
      [pvp_list_path]; %%, ...
  %%object_type{i_object}, filesep];

  for i_clip = 1 : length(clip_name)
    disp(clip_name{i_clip});
    
    output_clip_path = ...
	[output_object_path, ...
	   clip_name{i_clip}, filesep];
    mkdir(output_clip_path);
    
    input_clip_path = ...
	[input_object_path, ...
	   clip_name{i_clip}, filesep];
    mkdir(input_clip_path);
    
    list_clip_path = ...
	[list_object_path, ...
	 clip_name{i_clip}, filesep];
    list_path = list_clip_path;

    for i_version = 1 : length(version_str)
      disp(version_str{i_version});
      
      output_version_path = ...
	  [output_clip_path, ...
	   version_str{i_version}, filesep];
      mkdir(output_version_path);
      output_path = output_version_path;
      
      input_version_path = ...
	  [input_clip_path, ...
	   version_str{i_version}, filesep];
      mkdir(input_version_path);
      input_path = input_version_path;

      pvp_fileOfFrames_path = ...
	  [list_path];
      pvp_fileOfFrames_file = ...
	  [clip_name{i_clip}, "_", version_str{i_version}, "_", "fileOfFilenames.txt"];
      pvp_fileOfFrames = ...
	  [pvp_fileOfFrames_path, pvp_fileOfFrames_file];

      pvp_fileOfMasks_file = ...
	  [clip_name{i_clip}, "_", version_str{i_version}, "_", "fileOfMasknames.txt"];
      pvp_fileOfMasks = ...
	  [pvp_fileOfFrames_path, pvp_fileOfMasks_file];


      params_filename = ...
	  [DATASET_ID, ...
	   "_", ...
	   FLAVOR_ID, ...
	   "_", ...
	   object_type{i_object}, ...
	   pvp_num_ODD_kernels_str, pvp_bootstrap_str, ...
	   "_", ...
	   clip_name{i_clip}, ...
	   "_", ...
	   pvp_edge_type, ...
	   "_", ...
	   version_str{i_version}, ...
	   ".params"];


      [pvp_params_file] = ...
	  pvp_makeHeliParams(DATASET_ID, ...
			  FLAVOR_ID, ...
			  pvp_repo_path, ...
			  pvp_program_path, ...
			  input_path, ...
			  clip_name{i_clip}, ...
			  object_type{i_object}, ...
			  pvp_num_ODD_kernels, ...
			  pvp_bootstrap_str, ...
			  pvp_edge_type, ...
			  version_str{i_version}, ...
			  pvp_params_template, ...
			  pvp_frame_size, ...
			  pvp_num_frames, ...
			  list_path, ...
			  pvp_fileOfFrames, ...
			  pvp_fileOfMasks, ...
			  output_path, ...
			  params_filename);

      
    endfor
  endfor
endfor %% i_clip
