function [pvp_params_file, ...
	  pvp_params_dir] = ...
      pvp_makePetaVisionParamsFile(NEOVISION_DATASET_ID, ...
				   NEOVISION_DISTRIBUTION_ID, ...
				   pvp_repo_path, ...
				   pvp_program_path, ...
				   pvp_params_template, ...
				   pvp_clip_name, ...
				   pvp_object_type, ...
				   pvp_num_ODD_kernels, ...
				   pvp_edge_type)
  
  global PVP_VERBOSE_FLAG
  if ~exist("PVP_VERBOSE_FLAG") || isempty(PVP_VERBOSE_FLAG)
    PVP_VERBOSE_FLAG = 0;
  endif
  global pvp_home_path
  global pvp_mlab_path
  if isempty(pvp_home_path)
    pvp_home_path = ...
	[filesep, "home", filesep, "garkenyon", filesep];
  endif
  if isempty(pvp_mlab_path)
    pvp_mlab_path = ...
	[pvp_home_path, "workspace-indigo", filesep, "PetaVision", filesep, "mlab", filesep];
  endif

  more off;
  begin_time = time();

  num_input_args = 0
  num_input_args = num_input_args + 1;
  if nargin < num_input_args || ~exist("NEOVISION_DATASET_ID") || isempty(NEOVISION_DATASET_ID)
    NEOVISION_DATASET_ID = "Heli"; %% "Tower"; %% "Tail"; %% 
  endif
  neovision_dataset_id = tolower(NEOVISION_DATASET_ID); %% 
  num_input_args = num_input_args + 1;
  if nargin < num_input_args || ~exist("NEOVISION_DISTRIBUTION_ID") || isempty(NEOVISION_DISTRIBUTION_ID)
    NEOVISION_DISTRIBUTION_ID = "Formative"; %% "Training"; %%  "Challenge"; %%
  endif
  neovision_distribution_id = tolower(NEOVISION_DISTRIBUTION_ID); %% 
  num_input_args = num_input_args + 1;
  if nargin < num_input_args || ~exist("repo_path") || isempty(repo_path)
    pvp_repo_path = [filesep, "mnt", filesep, "data1", filesep, "repo", filesep];
  endif
  num_input_args = num_input_args + 1;
  if nargin < num_input_args || ~exist("program_path") || isempty(program_path)
    pvp_program_path = [pvp_repo_path, "neovision-programs-petavision", filesep];
  endif
  num_input_args = num_input_args + 1;
  if nargin < num_input_args || ~exist("pvp_params_template") || isempty(pvp_params_template)
    pvp_params_template = ...
	[pvp_program_path, ...
	 NEOVISION_DATASET_ID, filesep, ...
	 "params", filesep, "pvp_template.params"];
  endif

  pvp_params_dir = ...
      [pvp_program_path, ...
       NEOVISION_DATASET_ID, filesep, ...
       NEOVISION_DISTRIBUTION_ID, filesep, ...
       "params", filesep, ...
       pvp_clip_name, filesep, ...
       pvp_object_type, filesep, ...
       pvp_edge_type, filesep];
  pvp_params_file = ...
      [pvp_params_dir, ...
       NEOVISION_DATASET_ID, ...
       "_", ...
       pvp_object_type, ...
       pvp_num_ODD_kernels, ...
       "_", ...
       pvp_edge_str, ...
       ".params"];

  pvp_params_fid = ...
      fopen(pvp_params_file, "w");
  pvp_template_fid = ...
      fopen(pvp_params_template, "r");

  pvp_params_token = "$$$";
  pvp_key_params_str = ...
      {"numSteps", ...
       "imageListPath", ...
       "burstDuration", ...
       "endStim", ...
       "VgainL1", ...
       "VgainL2", ...
       "VgainL3", ...

       

  while(~feof(pvp_template_fid))
    pvp_template_str = gets(pvp_template_fid);
    for 
    if ~isempty(strfind(pvp_template_str, 
  endwhile


endfunction %% pvp_makePetaVisionParamsFile
