function [pvp_image] = pvp_drawBoundingBox(pvp_image, hit_list)

  num_hits = length(hit_list);
  for i_hit = 1 : num_hits
    pvp_image(hit_list{i_hit}.patch_Y1:hit_list{i_hit}.patch_Y2, ...
	      hit_list{i_hit}.patch_X1:hit_list{i_hit}.patch_X2, ...
	      2) = 255;
    pvp_image(hit_list{i_hit}.patch_Y2:hit_list{i_hit}.patch_Y3, ...
	      hit_list{i_hit}.patch_X2:hit_list{i_hit}.patch_X3, ...
	      2) = 255;
    pvp_image(hit_list{i_hit}.patch_Y3:hit_list{i_hit}.patch_Y4, ...
	      hit_list{i_hit}.patch_X3:hit_list{i_hit}.patch_X4, ...
	      2) = 255;
    pvp_image(hit_list{i_hit}.patch_Y4:hit_list{i_hit}.patch_Y1, ...
	      hit_list{i_hit}.patch_X4:hit_list{i_hit}.patch_X1, ...
	      2) = 255;
  endfor

endfunction %% pvp_drawBoundingBox