function [MNIST_images] = ...
      getMNIST(digit_id, ...
	       train_flag, ...
	       resize_factor, ...
	       nominal_ndx)

  if nargin < 1 || ~exist("digit_id") || isempty(digit_id)
    digit_id = 0;
  endif
  if nargin < 2 || ~exist("train_flag") || isempty(train_flag)
    train_flag = 0;
  endif
  if nargin < 3 || ~exist("resize_factor") || isempty(resize_factor)
    resize_factor = 1;
  endif
  if nargin < 4 || ~exist("nominal_ndx") || isempty(nominal_ndx)
    nominal_ndx = -1;  %% denotes that random digit_image will be returned
  endif

  MNIST_path = "/Users/gkenyon/MATLAB/MNIST/";
  if train_flag == 0
    MNIST_digits_filename = [MNIST_path, "t10k-images.idx3-ubyte"];
    MNIST_labels_filename = [MNIST_path, "t10k-labels.idx1-ubyte"];
  else
    MNIST_digits_filename = [MNIST_path, "train-images.idx3-ubyte"];
    MNIST_labels_filename = [MNIST_path, "train-labels.idx1-ubyte"];
  endif
  
  %% get labels
  [MNIST_labels, MNIST_ndx] = ...
      getMNISTlabels(train_flag, MNIST_labels_filename);
  
%% get digit image  
  [MNIST_images] = ...
      getMNISTdigits(digit_id, ...
		     MNIST_labels, ...
		     MNIST_ndx, ...
		     resize_factor, ...
		     nominal_ndx, ...
		     train_flag, ...
		     MNIST_digits_filename, ...
		     MNIST_labels_filename);

