#! /usr/bin/env python
# Usage: compareProbeOutput file1 file2 fieldindex
# file1 and file2 are CSV files, typically generated by PetaVision probes
# fieldindex is the (zero-indexed) field index to compare.

import csv, re, sys

if len(sys.argv) < 4:
  print("compareProbeOutput.py requires three filename arguments", file=sys.stderr)
  sys.exit(1)
if len(sys.argv) > 4:
  print("compareProbeOutput.py requires three filename arguments, but received an extra argument.", \
        file=sys.stderr)

paths = list()
csvread = list()
for k in range(2):
  try:
    paths.append(open(sys.argv[k+1], 'r'))
  except FileNotFoundError:
    print("compareProbeOutput.py: \"{}\" file not found".format(paths[k]), file=sys.stderr)
    sys.exit(1)

  csvread.append(csv.reader(paths[k], delimiter=','))

fieldindex = int(sys.argv[3]);

numdiffs = 0
linenumber = 0
eofA = False
eofB = False

while not (eofA or eofB):
  linenumber += 1
  try:
    lineA = next(csvread[0]);
  except StopIteration:
    eofA = True
  try:
    lineB = next(csvread[1]);
  except StopIteration:
    eofB = True

  if (eofA and eofB):
    break

  if (eofA and not eofB):
    print("compareProbeOutput.py: file 1 ended before file 2, at line number {}".format(linenumber), \
          file=sys.stderr)
    numdiffs += 1
    break

  if (eofB and not eofA):
    print("compareProbeOutput.py: file 2 ended before file 1, at line number {}".format(linenumber), \
          file=sys.stderr)
    numdiffs += 1
    break

  if len(lineA) != len(lineB):
    print("compareProbeOutput.py: Line {} has different lengths: length {} in file 1; length {} in file 2".format( \
          linenumber, len(lineA), len(lineB)), file=sys.stderr)
    print("  File 1: {}, File 2: {}".format(lineA, lineB), file=sys.stderr)
    numdiffs += 1
    continue

  # skip blank lines; we require that blank lines be in the same places in each file.
  if len(lineA) == 0:
    assert(len(lineB) == 0)
    continue

  if lineA[0] != lineB[0]:
    print("Line {} has different time values: t={} in file 1, t={} in file 2".format( \
          linenumber, lineA[0], lineB[0]), file=sys.stderr)
    numdiffs += 1
    break

  # If the line begins with a letter, assume it's a header and require that the lines be the same in each file.
  if len(lineA[0]) == 0 or re.match(' *[A-Za-z]', lineA[0]) or len(lineB[0])== 0 or re.match(' *[A-Za-z]', lineB[0]):
    for k in range(len(lineA)):
      if lineA[k] != lineB[k]:
        print("Line {}, field {} differs:\n  Line A=\"{}\"\n  Line B=\"{}\"".format(linenumber, k, lineA[k], lineB[k]))
    continue

  valueA = float(lineA[fieldindex])
  valueB = float(lineB[fieldindex])
  discrep = abs(valueB - valueA)
  if discrep > 1e-6 * abs(valueA):
    print("Line {} has significantly different probe values: {} in file 1, {} in file 2".format( \
          linenumber, valueA, valueB), file=sys.stderr)
    numdiffs += 1
    continue

if numdiffs > 0:
  print("Files \"{}\" and \"{}\" differ".format(paths[0].name, paths[1].name), file=sys.stderr)
  sys.exit(1)
else:
  sys.exit(0)
