  if strcmp(run_type, "Heli_DPTX3") 
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% Heli_DPTX3 list
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    ReconError_list = ...
        {["a3_"], ["ReconV1"]; ...
         ["a9_"], ["ReconInfraV2"]; ...
         ["a16_"], ["ReconInfraV4"]};
    num_ReconError_list = size(ReconError_list,1);
    ReconError_skip = repmat(1, num_ReconError_list, 1);
    ReconError_skip(1) = 1;
    ReconError_skip(2) = 1;
    ReconError_skip(3) = 1;
    ReconError_norm_list = ...
        {["a0_"], ["Image"]; ...
         ["a0_"], ["Image"]; ...
         ["a0_"], ["Image"]};
    ReconError_norm_strength = ones(num_ReconError_list,1);
    ReconError_norm_strength = ...
	[1/sqrt(18*18); 1/sqrt(18*18); 1/sqrt(18*18)];
    ReconError_RMS_fig_ndx = [1 1 1];  %% causes recon error to be overlaid on specified  nonSparse (Error) figure
  elseif strcmp(run_type, "PASCAL_DPT") 
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% PASCAL_DPT list
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    ReconError_list = ...
        {["a3_"],  ["ImageReconS1"]; ...
         ["a8_"],  ["ImageReconS2"]; ...
         ["a13_"],  ["ImageReconS3"]; ...
         ["a10_"],  ["ImageReconS1ReconS2"]; ...
         ["a18_"],  ["ImageReconS2ReconS3"]}; 
    num_ReconError_list = size(ReconError_list,1);
    ReconError_skip = repmat(1, num_ReconError_list, 1);
    ReconError_norm_list = ...
        {["a0_"], ["Image"]; ...
         ["a0_"], ["Image"]; ...
         ["a0_"], ["Image"]; ...
         ["a0_"], ["Image"]; ...
         ["a0_"], ["Image"]}; 
    ReconError_norm_strength = ...
	[1/sqrt(18*18*3); 1/sqrt(18*18*3); 1/sqrt(18*18*3); 1/sqrt(18*18*3); 1/sqrt(18*18*3)];
    ReconError_RMS_fig_ndx = [1 1 1 1 1];%% 1];
  endif %% run_type
  
  if ~isempty(ReconError_list)
  [nonSparse_times_array, ...
   nonSparse_RMS_array, ...
   nonSparse_norm_RMS_array, ...
   ReconError_RMS_fig] = ...
      analyzeReconErrorPVP(ReconError_list, ...
			   ReconError_skip, ...
			   ReconError_norm_list, ...
			   ReconError_norm_strength, ...
			   nonSparse_times_array, ...
			   nonSparse_RMS_array, ...
			   nonSparse_norm_RMS_array, ...
			   nonSparse_RMS_fig, ...
			   ReconError_RMS_fig_ndx, ...
			   output_dir, ...
			   plot_flag, ...
			   fraction_nonSparse_frames_read, ...
			   min_nonSparse_skip, ...
			   fraction_nonSparse_progress);
  drawnow;
  endif
