tar -czf /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/tar_amoeba2_2FC_t.tar.gz /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/2FC/t/* && rm -R  /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/2FC/t/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/tar_amoeba2_4FC_t.tar.gz /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/4FC/t/* && rm -R  /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/4FC/t/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/tar_amoeba2_6FC_t.tar.gz /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/6FC/t/* && rm -R  /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/6FC/t/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/tar_amoeba2_8FC_t.tar.gz /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/8FC/t/* && rm -R  /mnt/data/repo/neovision-programs-petavision/amoeba2/3way/activity/8FC/t/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/tar_noamoeba2_2FC_d.tar.gz /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/2FC/d/* && rm -R  /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/2FC/d/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/tar_noamoeba2_4FC_d.tar.gz /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/4FC/d/* && rm -R  /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/4FC/d/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/tar_noamoeba2_6FC_d.tar.gz /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/6FC/d/* && rm -R  /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/6FC/d/* &
tar -czf /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/tar_noamoeba2_8FC_d.tar.gz /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/8FC/d/* && rm -R  /mnt/data/repo/neovision-programs-petavision/noamoeba2/3way/activity/8FC/d/* &

