#!/bin/bash
while getopts ":pl" opt; do
    case $opt in
        p)
            PHASE=true
            ;;
	l) 
	    LEGEND=true
	    ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "$1" ]
then
    echo "Please enter a params file to draw:"
    read pfile
fi
if [ ! -z "$1" ]
then
    pfile=$1
fi
if [ ! -f $1 ]
then
    echo "$1 not found."
    exit 1
    if [ ! -f $pfile ]
    then
	echo "$pfile not found."
	exit 1
    fi
fi

olddir=$PWD
cd ${0%/*}
plabdir=$PWD
cd $olddir
parentdir="$(dirname "$plabdir")"
if [ "$PHASE" = true ] ; then
    if [ "$LEGEND" = true ] ; then
	python $plabdir/param_draw.py -l $parentdir/src/layers -c $parentdir/src/connections $pfile -p --legend
    else
	python $plabdir/param_draw.py -l $parentdir/src/layers -c $parentdir/src/connections $pfile -p
    fi
else
    if [ "$LEGEND" = true ] ; then
        python $plabdir/param_draw.py -l $parentdir/src/layers -c $parentdir/src/connections $pfile --legend
    else
	python $plabdir/param_draw.py -l $parentdir/src/layers -c $parentdir/src/connections $pfile
    fi
fi

mermaid param_graph
rm param_graph
filename=$(basename "$pfile")
extension="${filename##*.}"
filename="${filename%.*}"
mv param_graph.png "$filename.png"
open "$filename.png"
