PVP_FILE_TYPE = 1;
PVP_ACT_FILE_TYPE = 2;
PVP_WGT_FILE_TYPE = 3;
PVP_KERNEL_FILE_TYPE = 5;
PVP_NONSPIKING_ACT_FILE_TYPE = 4;

global NUM_BIN_PARAMS
global NUM_WGT_PARAMS

NUM_BIN_PARAMS = 20;
NUM_WGT_PARAMS = 6;

