function [target_struct] = ...
      pvp_setTargetStruct(layer, ...
			  epoch_struct, ...
			  layer_struct, ...
			  target_struct, ...
			  rate_array)

  global pvp_order
  global N NROWS NCOLS % for the current layer
  global NFEATURES  % for the current layer
  
  NCOLS = layer_struct.num_cols(layer);
  NROWS = layer_struct.num_rows(layer);
  NFEATURES = layer_struct.num_features(layer);
  N = layer_struct.num_neurons(layer);
  
  %% segment targets/clutter for each layer  
  use_max = 1;  % rate not available unless read in all epochs first
  target_struct.bkgrnd_ndx_all{layer,1} = ...
      find(ones(layer_struct.num_neurons(layer),1));
  target_struct.bkgrnd_ndx_max{layer,1} = ...
      find(ones(layer_struct.num_neurons(layer),1));
  stim_steps = ...
      epoch_struct.stim_begin_step(layer) : epoch_struct.stim_end_step(layer);
  for i_target = 1:target_struct.num_targets
    if isempty(target_struct.target{i_target})
      continue
    endif
    [target_struct.target_ndx_all{layer, i_target}, ...
     target_struct.target_ndx_max{layer, i_target}] = ...
        pvp_image2layer( layer, target_struct.target{i_target}, ...
			stim_steps, use_max, rate_array{layer}, pvp_order);
    target_struct.num_target_neurons_max(layer, i_target) = ...
        length( target_struct.target_ndx_max{layer, i_target} );
    target_struct.num_target_neurons_all(layer, i_target) = ...
        length( target_struct.target_ndx_all{layer, i_target} );
    target_struct.bkgrnd_ndx_all{layer}(target_struct.target_ndx_all{layer, i_target}) = 0;
    target_struct.bkgrnd_ndx_max{layer}(target_struct.target_ndx_max{layer, i_target}) = 0;
  endfor %% % i_target
  
  if ~isempty(target_struct.clutter)
    [target_struct.clutter_ndx_all{layer}, target_struct.clutter_ndx_max{layer}] = ...
	pvp_image2layer( layer, target_struct.clutter, stim_steps, ...
			use_max, rate_array{layer}, pvp_order);
    target_struct.num_clutter_neurons_max(layer,1) = ...
	length( target_struct.clutter_ndx_max{layer} );
    target_struct.num_clutter_neurons_all(layer,1) = ...
	length( target_struct.clutter_ndx_all{layer} );
  
    target_struct.bkgrnd_ndx_all{layer}(target_struct.clutter_ndx_all{layer}) = 0;
    target_struct.bkgrnd_ndx_max{layer}(target_struct.clutter_ndx_max{layer}) = 0;
  endif
  
  target_struct.bkgrnd_ndx_all{layer} = find(target_struct.bkgrnd_ndx_all{layer});
  target_struct.bkgrnd_ndx_max{layer} = find(target_struct.bkgrnd_ndx_max{layer});
  target_struct.num_bkgrnd_neurons_all(layer) = ...
      length( target_struct.bkgrnd_ndx_all{layer} );
  target_struct.num_bkgrnd_neurons_max(layer) = ...
      length( target_struct.bkgrnd_ndx_max{layer} );

